### ISSUE TITLE
502 Bad gateway after installtion

### ISSUE THREAD

**Issue by anmol26s** [magikcypress/telegram_ynh#1]
Hi 
I am getting 502 Bad gateway error.

Here is the installation log

https://datamol.in/zerobin/?7955a74fbe63cc96#THTI+0Cm/21OhN/q44C2ARKpSLibJFtkHnIeTmHAxGU=

**Comment by magikcypress** [comment]
Hello,

Thanks for your debug ;) I fix it !

Regards

**Comment by anmol26s** [comment]
Hi,
I still can not use it. Its shows 404 not found error
Here is the log:
https://datamol.in/zerobin/?9b2b4389cb78a4ca#hVjLpA1OxEOZz0pTkglf/7AsUPZsJMknjGVMR+u0psk=

**Comment by magikcypress** [comment]
Sorry, can you push your zerobin with log error please.

**Comment by anmol26s** [comment]
Here is the log error again

https://datamol.in/zerobin/?684f0f997425b029#BUgVqwM27GpClvMnRrRNP2+cqeZEI2ywNw4LpusYopo=

Thanks

**Comment by magikcypress** [comment]
The /dev/tty 'special file' has been removed.

Solution
$ mknod -m 644 /dev/tty c 5 0

This creates /dev/tty but only allows root to use it, run chmod a+rw /dev/tty

**Comment by anmol26s** [comment]
I tired to to make /dev/tty and then ram chmod a+rw /dev/tty
But the I still get the error 502 bad gateway.

Further there is no folder naming telegram in /var/www/ and there is no database for the telegram in phpmysql.

Can you please suggest solutions.

Thanks

**Comment by magikcypress** [comment]
You manage to show telegram on 127.0.0.1:8000 in your browser?
Gulp listening well on 8000 on your server?
No file system for telegram, telegram listening on port 8000
