### ISSUE TITLE
install KO

### ISSUE THREAD

**Issue by isAAAc** [magikcypress/telegram_ynh#2]
/home/admin# yunohost app install https://github.com/magikcypress/telegram_ynh
Erreur : L'application est incompatible avec votre version de YunoHost : Le paquet de l'application doit être mis à jour pour suivre les changements de YunoHost

:/

/home/admin# yunohost --version
yunohost: 2.4.2
yunohost-admin: 2.4.2
moulinette: 2.4.0.1
ssowat: 2.6.0

**Comment by magikcypress** [comment]
Hello,

Thanks for reporting bug version.
I fixed script for install, remove and manifest.json

enjoy

**Comment by isAAAc** [comment]
thx for your work, 
but install is still ko : 
```
Attention : spip n'est pas installé
Attention : !!
Attention :   telegram install's script has encountered an error. Installation was cancelled.
Attention : !!
Erreur : Échec de l'installation
```
do you want a new ticket ? more logs ?

**Comment by magikcypress** [comment]
Hello,

I fixed a SPIP informations for install and upgrade. probably install problem?
If you have more log, please send in this ticket.

Thanks

**Comment by isAAAc** [comment]
evolution :) : 
`# yunohost app install telegram
Erreur : L'application est incompatible avec votre version de YunoHost : Le paquet de l'application doit être mis à jour pour suivre les changements de YunoHost
`

**Comment by magikcypress** [comment]
Hello,

on my server this install is correct.

```
$ yunohost --version
   yunohost: 2.5.4
   yunohost-admin: 2.5.1
   moulinette: 2.5.2
   ssowat: 2.6.1
```
if you can update yunohost version, this app must install correctly.

**Comment by isAAAc** [comment]
# yunohost --version
yunohost: 2.5.4
yunohost-admin: 2.5.1
moulinette: 2.5.2
ssowat: 2.6.1

same version here... that's strange ... wich log could help ?

**Comment by magikcypress** [comment]
You have a error log in /var/log/yunohost ?

**Comment by isAAAc** [comment]
# more /var/log/yunohost/yunohost-cli.log
...
2017-02-06 14:05:08,677 INFO     moulinette.actionsmap process - processing action [10244.1]: yunohost.app.install
2017-02-06 14:05:08,695 INFO     yunohost.app _fetch_app_from_git - [10244.1] Téléchargement...
2017-02-06 14:05:09,454 INFO     yunohost.app _extract_app_from_file - [10244.1] Extraction...
2017-02-06 14:05:09,462 INFO     yunohost.app _extract_app_from_file - [10244.1] Terminé
2017-02-06 14:05:09,465 ERROR    yunohost cli - L'application est incompatible avec votre version de YunoHost : Le paquet de l'application doit être mis à jour pour suivre les changements de 
YunoHost

not enought verbose ... is it ?

**Comment by magikcypress** [comment]
clean /etc/yunohost/apps/telegram/, after start a new install ?

**Comment by isAAAc** [comment]
no change :/

**Comment by magikcypress** [comment]
```
# yunohost app install https://github.com/magikcypress/telegram_ynh
Choose a domain for Telegram: yunohost.local
Choose a path for Telegram (default: /telegram): 
Choose the Telegram administrator (must be an existing YunoHost user): cyp
Success! The SSOwat configuration has been generated
Success! Installation complete
```

**Comment by isAAAc** [comment]
i qdded the community app list , that's why i used 
`#yunohost app install telegram `

using
`# yunohost app install https://github.com/magikcypress/telegram_ynh`
is better, app installed, \o/

but still have a 502 bad gateway error in the browser

**Comment by magikcypress** [comment]
Good!
telegram is installed on your server ?

**Comment by isAAAc** [comment]
it should ...
but no telegram folder in /var/www
```
# ls /etc/yunohost/apps/telegram/
manifest.json  scripts/       settings.yml   status.json 
```

how to resolv the 502 error in nginx ?

**Comment by magikcypress** [comment]
normal, no directory install here!
webogram listen of 8000

nginx use proxy_pass for that.

`proxy_pass http://127.0.0.1:8000/app;`

**Comment by isAAAc** [comment]
i don't understand where i should put this ?

**Comment by magikcypress** [comment]
you need to install webogram to run this apps
you launch webogram, and you should have access to telegram in your browser.

https://github.com/zhukov/webogram/

**Comment by isAAAc** [comment]
oh ! ok i see, 
i install it right now

**Comment by isAAAc** [comment]
i created a new "my_webapp" and used git to get it
`git clone https://github.com/zhukov/webogram/ /var/www/my_webapp__2/www`
and then as said in the readme :
```
npm install -g gulp
npm install
```
but the webapp url gives me this error : 
```
403 Forbidden
nginx
```

where am i wrong ?

**Comment by magikcypress** [comment]
@isAAAc I worked to allow the installation of telegram on YunoHost. 

Good install
